title: ML-facial-recognition-starter
hero_image: images/banner.png
description: ML-facial-recognition-starter description
version: 4
listed: false
copyedit: false
last_tested: "2020-11-24"
steps:
  - title: Introduction
  - title: A different kind of Scratch
  - title: Using extensions
  - title: Making the mask
  - title: What next?
