title: Funny Face Follower
hero_image: images/banner.png
description: Use Machine Learning to hide your face with a mask that will follow you when you move!
version: 4
listed: false
copyedit: false
last_tested: "2020-11-24"
steps:
  - title: Introduction
  - title: Facial recognition with Scratch
  - title: Make a mask
  - title: What next?
